Impl get_object & authentication
instrumentisto/baza pull request #17
Opened 2022-08-09 13:59 UTC by xDarksome

## Synopsis

`get_object` operation is missing.

## Solution

Impl `get_object` operations & authentication.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains issue reference
    - [x] Has type and `k::` labels applied
- Before [review][l:4]:
    - [ ] Documentation is updated (if required)
    - [ ] Tests are updated (if required)
    - [ ] Changes conform [code style][l:2]
    - [ ] [CHANGELOG entry][l:3] is added (if required)
    - [ ] FCM (final commit message) is posted or updated
    - [ ] [Draft mode][l:1] is removed
- [ ] [Review][l:4] is completed and changes are approved
    - [ ] FCM (final commit message) is approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: /CONTRIBUTING.md#code-style
[l:3]: /CHANGELOG.md
[l:4]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-08-09 14:11 UTC, xDarksome commented
FCM
---
```
Implement GetObject operation & authentication (#17)
```

2022-08-09 14:17 UTC, xDarksome commented
@tyranron `GET` requests don't work without authentication. 
`POST` requests should not work as well, but they are currently working because of a `s3-server` bug. The bug is fixed, but not yet released.

We don't actually care about authentication, so it is added just to comply with s3 API requirements.

2022-08-09 15:59 UTC, tyranron requested changes

2022-08-09 15:59 UTC, tyranron commented on api/s3/src/lib.rs
> +            body: Some(bytes.into()),
`GetObjectOutput` supports streaming body, which we definitely should use to response in a buffered manner instead of loading the whole file at once.

2022-08-10 10:32 UTC, tyranron requested changes
@xDarksome I've corrected E2E scenarios' look. Please, update the test code.

Anything else seems fine.

2022-08-10 12:30 UTC, merged