Impl helm chart
instrumentisto/baza pull request #3
Opened 2022-06-30 08:09 UTC by xDarksome

## Synopsis

<Give a brief overview of the problem>

## Solution

<Describe how exactly the problem is (or will be) resolved>

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [ ] Name contains issue reference
    - [x] Has type and `k::` labels applied
- Before [review][l:4]:
    - [ ] Documentation is updated (if required)
    - [ ] Tests are updated (if required)
    - [ ] Changes conform [code style][l:2]
    - [ ] [CHANGELOG entry][l:3] is added (if required)
    - [ ] FCM (final commit message) is posted or updated
    - [ ] [Draft mode][l:1] is removed
- [ ] [Review][l:4] is completed and changes are approved
    - [ ] FCM (final commit message) is approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: /CONTRIBUTING.md#code-style
[l:3]: /CHANGELOG.md
[l:4]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-06-30 12:58 UTC, xDarksome commented
FCM
---
```
Implement Helm chart (#3)
```

2022-06-30 17:01 UTC, tyranron commented on helm/baza/templates/statefulset.yaml
> +      dnsPolicy: ClusterFirstWithHostNet
No need for `hostNetwork` here.

2022-06-30 17:04 UTC, tyranron requested changes

2022-07-01 08:04 UTC, xDarksome commented on helm/baza/templates/statefulset.yaml
> +        - name: baza
@tyranron I thought it was gonna be a separate thing. In our specific case we actually need Openresty for JWT validation, while someone else might want to use it with Nginx or something else.

2022-07-01 10:50 UTC, tyranron commented on helm/baza/templates/statefulset.yaml
> +        - name: baza
@xDarksome yah, but deploying it separately will be cumbersome. We still need to provide Nginx container for reading files directly on a separate port. And in our custom deployment we may substitute the image to OpenResty and provide custom config.

2022-07-08 09:40 UTC, tyranron approved these changes

2022-07-08 09:47 UTC, merged